dev:
  catalog: mlops_dev
  schema: yilmazfs
  volume: arxiv_files
  llm_endpoints: databricks-llama-4-maverick
  embedding_endpoint: databricks-gte-large-en
  vector_search_endpoint: llmops_course_vs_endpoint
